services:
  - type: web
    name: spring-boot-gradle-app
    env: java
    buildCommand: "./gradlew build -x test"
    startCommand: "java -jar build/libs/CommonService-0.0.1-SNAPSHOT.jar"
    branch: main
    plan: free
